services:
  - type: web
    name: gerot-dashboard
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    numInstances: 1
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MS_TENANT_ID
        value: ""
      - key: MS_CLIENT_ID
        value: ""
      - key: MS_CLIENT_SECRET
        value: ""
      - key: MS_PLANNER_PLAN_ID
        value: ""
      - key: MS_PLANNER_BUCKET_ID
        value: ""
      - key: DATABASE_URL
        value: postgresql://postgres.cwkfsazxmtdluoexwafp:uTwmiAmgkXlTa0Yu@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: DIRECT_URL
        value: postgresql://postgres.cwkfsazxmtdluoexwafp:uTwmiAmgkXlTa0Yu@aws-1-us-east-2.pooler.supabase.com:5432/postgres
      - key: USE_TAILWIND_THEME
        value: "true"

